[build]
  command = "yarn build"
  publish = "Frontend/build"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  [plugins.inputs]
    dataDir = "data/feeds"
    feeds = "[]" # Placeholder to satisfy plugin validation.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
